# cloudbuild.yaml

steps:
  # This is an example step. Replace it with your actual build steps.
  # For instance, if you're building a Docker image and pushing it to Artifact Registry:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA']

# This section configures logging when a custom service account is used with a trigger.
# It directs all build logs to Cloud Logging, which is accessible in the Google Cloud Console.
options:
  logging: CLOUD_LOGGING_ONLY
