# cloudbuild.yaml

# steps:
#   # This is an example step. Replace it with your actual build steps.
#   # For instance, if you're building a Docker image and pushing it to Artifact Registry:
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA', '.']

#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA']

# # This section configures logging when a custom service account is used with a trigger.
# # It directs all build logs to Cloud Logging, which is accessible in the Google Cloud Console.
# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
  # Build the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA']

  # Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'brainwave-problem7' # Replace with your Cloud Run service name
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA'
      - '--region'
      - 'us-central1' # Replace with the region where you want to deploy (e.g., us-central1, europe-west1)
      # Uncomment the line below if you want to allow unauthenticated access to your service
      # - '--allow-unauthenticated'

# This section configures logging when a custom service account is used with a trigger.
# It directs all build logs to Cloud Logging, which is accessible in the Google Cloud Console.
options:
  logging: CLOUD_LOGGING_ONLY

# This 'images' field is important for Cloud Build to track the output images.
# It should list the full path of the Docker image that is produced by the build.
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/my-image:$COMMIT_SHA'
